apiVersion: v2
name: cubestack-portal-chart
description: A Helm chart for deploying CubeStack Portal (UI)

type: application

version: 1.0.0
appVersion: "1.0.0"

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/keywords: cubestack, portal, ui, web
