#!/usr/bin/env bash
# Regenerates the static content of helm/cubestack-controller-manager-chart from the kustomize
# sources in config/. Idempotent: run after any change under config/ and commit
# the chart. CI runs this script and fails on git diff (make helm-resources-check).
#
# The script manages only templates/ (kustomize split) + vap.yaml. The
# ai.cubestack.io CRDs in crds/ are NOT stored in the repo — they are copied
# from config/crd/bases at use time by `make helm-crds-sync` (a prereq of
# helm-package / helm-e2e-install). The leaderworkerset/disaggregatedset CRDs
# are NOT shipped by the chart — they come with the upstream LeaderWorkerSet
# controller prerequisite (hack/install-lws-controller.sh applies the pinned
# lws module's config/default, which includes its own CRDs).
#
# Requires helm on PATH: after regenerating, the script renders the chart with
# helm template to validate the values-driven gateway args (section 3).
set -euo pipefail
cd "$(dirname "$0")/.."          # operator/
OP="${PWD}"
CHART="${OP}/helm/cubestack-controller-manager-chart"
TEMPLATES="${CHART}/templates"
RENDER_DIR="$(mktemp -d)"

# Start from an empty templates/ so objects that disappear from the kustomize
# output (or config/vap) have their stale template files removed — the drift
# gate only sees deletions the regenerator itself produces.
rm -rf "${TEMPLATES}"
mkdir -p "${TEMPLATES}"

# --- 1. VAPs: verbatim from config/vap (source of truth, unprefixed) ---
# Join with explicit "---" separators: each source file is its own multi-doc
# stream, and without a separator the last doc of one file would merge into
# the first doc of the next (duplicate keys are silently overwritten by the
# YAML decoders helm uses, dropping whole documents).
{
  cat "${OP}"/config/vap/modelversion_policy.yaml
  for f in "${OP}"/config/vap/inferenceruntimeprofile_policy.yaml \
           "${OP}"/config/vap/inferenceservice_policy.yaml; do
    printf -- '---\n'
    cat "${f}"
  done
} > "${TEMPLATES}"/vap.yaml
sed -i '1i # Generated by hack/update-helm-resources.sh — DO NOT EDIT' "${TEMPLATES}"/vap.yaml

# --- 2. RBAC / manager / metrics Service: split kustomize build output ---
if [ ! -x "${OP}/bin/kustomize" ]; then
  make -s -C "${OP}" kustomize
fi
OUT="$(mktemp)"
trap 'rm -rf "${OUT}" "${RENDER_DIR}"' EXIT
"${OP}/bin/kustomize" build "${OP}/config/default" > "${OUT}"

# Rewrite the manager image to values references. The images transformer in
# config/manager/kustomization.yaml already rewrote controller:latest to
# example.com/cubestack:v0.0.1 in the build output.
#
# `#` not `|` as the s/// delimiter: the replacement's `default` call is a pipe.
# The empty tag falls back to the chart's appVersion, which is what makes a
# released chart pull the manager image released with it.
sed -i 's#^\(\s*\)image: example\.com/cubestack:v0\.0\.1$#\1image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"#' "${OUT}"
# Fail loudly if the needle above matched nothing: a silent no-op would leave a
# stale hardcoded image in the chart while the drift gate stays green.
grep -q 'image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"' "${OUT}" \
  || { echo "image rewrite no-op'd — update needle in update-helm-resources.sh"; exit 1; }
# Replace the hardcoded namespace (metadata + binding subjects) with the release ns.
sed -i 's|namespace: cubestack-system|namespace: {{ .Release.Namespace }}|g' "${OUT}"

# Rewrite the manager's platform-Gateway args into values-driven Go template
# conditionals: --gateway-name (a literal from the config/manager base) becomes
# a {{- with .Values.gateway.name }} block, and the flags deliberately absent
# from the kustomize base, see config/manager/manager.yaml — the catalog
# hostname and the dataplane namespace — are injected as
# {{- if/with .Values.gateway.* }} blocks.
# Each flag renders only while its value is non-empty, so an empty name
# reproduces the unconfigured state (publishing off).
#
# --gateway-namespace is the exception: it renders unconditionally, from
# .Values.gateway.namespace, and with `| default` rather than a {{- with }}
# guard. The namespace is not a switch like the catalog hostname — it names the
# namespace the platform put the Gateway in, which this manager is pointed at —
# and an omitted flag does not mean "unconfigured": cmd/main.go defaults it to
# cubestack-system and devenvironment_controller.go's defaultedConfig falls back
# to the same, so a release that rendered no flag at all would silently aim
# every environment at a namespace nobody configured. `| default` is also what
# keeps an emptied value — or a release upgraded with --reuse-values, whose
# stored values carry no gateway.namespace key — from rendering a bare
# --gateway-namespace= and reaching that same fallback. The default is where the
# platform's Gateway lives, not the release namespace, which is where this chart
# used to create it.
#
# None of this creates anything: the chart ships no Gateway and no
# ClientTrafficPolicy. Section 2d used to rewrite their names — that whole
# section is gone, because those objects belong to the platform, are not in
# config/default, and so never reach the splitter above.
#
# The DevEnvironment L4 port pool flags are rewritten the same way, but
# unconditionally: the pool always has a range, so .Values.l4PortRange.start/end
# are always passed. The RDMA extended resource flags follow that pattern for
# the same reason — a name always exists, and the cluster's device plugin
# ConfigMap, not this chart, is what defines it.
awk '
/^[[:space:]]*- --gateway-name=cubestack-gateway$/ {
  if (gateway_name++) { print "duplicate --gateway-name line in kustomize output" > "/dev/stderr"; exit 1 }
  ind = substr($0, 1, index($0, "-") - 1)
  print ind "{{- with .Values.gateway.name }}"
  print ind "- --gateway-name={{ . }}"
  print ind "{{- end }}"
  print ind "- --gateway-namespace={{ .Values.gateway.namespace | default \"envoy-gateway-system\" }}"
  print ind "{{- with .Values.gateway.dataplaneNamespace }}"
  print ind "- --gateway-dataplane-namespace={{ . }}"
  print ind "{{- end }}"
  print ind "{{- if .Values.gateway.catalogHostname }}"
  print ind "- --gateway-catalog-hostname={{ .Values.gateway.catalogHostname }}"
  print ind "{{- end }}"
  next
}
/^[[:space:]]*- --gateway-namespace=envoy-gateway-system$/ {
  if (gateway_name != 1) { print "--gateway-namespace seen without --gateway-name" > "/dev/stderr"; exit 1 }
  if (gateway_namespace++) { print "duplicate --gateway-namespace line in kustomize output" > "/dev/stderr"; exit 1 }
  next
}
/^[[:space:]]*- --l4-port-range-start=[0-9]+$/ {
  if (l4_start++) { print "duplicate --l4-port-range-start line in kustomize output" > "/dev/stderr"; exit 1 }
  ind = substr($0, 1, index($0, "-") - 1)
  print ind "- --l4-port-range-start={{ .Values.l4PortRange.start }}"
  next
}
/^[[:space:]]*- --l4-port-range-end=[0-9]+$/ {
  if (l4_end++) { print "duplicate --l4-port-range-end line in kustomize output" > "/dev/stderr"; exit 1 }
  ind = substr($0, 1, index($0, "-") - 1)
  print ind "- --l4-port-range-end={{ .Values.l4PortRange.end }}"
  next
}
/^[[:space:]]*- --rdma-ib-resource=rdma\/ib_shared_devices$/ {
  if (rdma_ib++) { print "duplicate --rdma-ib-resource line in kustomize output" > "/dev/stderr"; exit 1 }
  ind = substr($0, 1, index($0, "-") - 1)
  print ind "- --rdma-ib-resource={{ .Values.rdma.ibResource }}"
  next
}
/^[[:space:]]*- --rdma-roce-resource=rdma\/roce_shared_devices$/ {
  if (rdma_roce++) { print "duplicate --rdma-roce-resource line in kustomize output" > "/dev/stderr"; exit 1 }
  ind = substr($0, 1, index($0, "-") - 1)
  print ind "- --rdma-roce-resource={{ .Values.rdma.roceResource }}"
  next
}
{ print }
END {
  # Fail loudly if the needles above matched nothing (e.g. the args in
  # config/manager/manager.yaml changed): a silent no-op would ship a chart
  # whose publish feature cannot be enabled by values while the drift gate
  # stays green.
  if (gateway_name != 1 || gateway_namespace != 1) {
    print "gateway args not found in kustomize output — update needle in update-helm-resources.sh" > "/dev/stderr"
    exit 1
  }
  if (l4_start != 1 || l4_end != 1) {
    print "l4 port range args not found in kustomize output — update needle in update-helm-resources.sh" > "/dev/stderr"
    exit 1
  }
  if (rdma_ib != 1 || rdma_roce != 1) {
    print "rdma resource args not found in kustomize output — update needle in update-helm-resources.sh" > "/dev/stderr"
    exit 1
  }
}
' "${OUT}" > "${OUT}.gw" && mv "${OUT}.gw" "${OUT}"

awk -v out="${TEMPLATES}" '
function flush() {
  if (buf == "") return
  # Skip objects not owned by the chart templates/: CRDs (installed via the
  # chart crds/ dir, populated by helm-crds-sync), VAPs/VAP bindings (written
  # above from config/vap) and Namespace.
  if (kind == "CustomResourceDefinition" || kind == "ValidatingAdmissionPolicy" || kind == "ValidatingAdmissionPolicyBinding" || kind == "Namespace") { buf=""; kind=""; name=""; return }
  base = tolower(kind) "-" name
  gsub(/[^a-z0-9-]/, "-", base)
  fn = out "/" base ".yaml"
  print "# Generated by hack/update-helm-resources.sh — DO NOT EDIT" > fn
  printf "%s\n", buf > fn
  close(fn)
  buf=""; kind=""; name=""
}
/^---$/ { flush(); next }
# Capture the first kind and first two-space-indented name of each doc (the
# metadata.name); apiVersion is the first line, so capture must not depend on
# the buffer being empty.
{ if (kind == "" && $0 ~ /^kind: /) kind = $2
  if (name == "" && $0 ~ /^  name: /) name = $2
  buf = buf $0 "\n" }
END { flush() }
' "${OUT}"
rm -f "${OUT}"

# --- 3. Validate the values-driven chart content (manager gateway args, absence of the platform's objects) ---
# The manager's platform-Gateway args are injected into the deployment
# template from .Values.gateway (section 2 rewrite). Assert the rendered args
# for every value combination that changes behavior: defaults pass name and
# the dataplane namespace but no catalog hostname; an explicit hostname is
# passed verbatim; an emptied name or dataplane namespace drops its flag; and
# emptying those reproduces the publish-off state — no --gateway-name, no
# --gateway-catalog-hostname, no --gateway-dataplane-namespace (RouteReady=False,
# GatewayNotConfigured, and environments left default-deny inbound). The
# namespace is not in that set: it always renders, from .Values.gateway.namespace,
# because an omitted flag would leave the manager's own cubestack-system default
# in force. A silent no-op here would ship a chart whose publish feature cannot
# be enabled by values.
#
# The Gateway and the ClientTrafficPolicy are asserted ABSENT below: both belong
# to the platform now. A stray resource added back under config/default, or a
# template left behind under templates/, would put this chart back in the
# business of owning an object whose lifecycle the platform decides — and
# nothing else in this script would notice.
command -v helm >/dev/null 2>&1 || { echo "helm not found — required to validate the rendered chart (section 3 of update-helm-resources.sh)"; exit 1; }
# expect_render <case> <present|absent> <grep pattern (anchored at the arg line)> [helm --set args...]
expect_render() {
  local what="$1" presence="$2" pattern="$3"
  shift 3
  local file="${RENDER_DIR}/${what}.yaml"
  helm template cubestack "${CHART}" "$@" > "${file}" || { echo "helm template failed for case '${what}' (section 3)"; exit 1; }
  if grep -Eq -- "${pattern}" "${file}"; then
    [ "${presence}" = present ] || { echo "gateway args render check failed: ${what} unexpectedly rendered ${pattern}"; exit 1; }
  else
    [ "${presence}" = absent ] || { echo "gateway args render check failed: ${what} did not render ${pattern}"; exit 1; }
  fi
}
# Defaults: the convention values are passed; the catalog hostname stays unset
# (publish off).
# --namespace cubestack-system keeps these renders comparable to a real install
# of this chart; without it .Release.Namespace is helm's "default".
expect_render defaults present '^[[:space:]]*- --gateway-name=cubestack-gateway$' --namespace cubestack-system
expect_render defaults present '^[[:space:]]*- --gateway-namespace=envoy-gateway-system$' --namespace cubestack-system
expect_render defaults absent  '^[[:space:]]*- --gateway-catalog-hostname=' --namespace cubestack-system
# The dataplane namespace is passed by default: it is what lets the DevEnvironment
# controller admit the Gateway's proxies into environment pods.
expect_render defaults present '^[[:space:]]*- --gateway-dataplane-namespace=envoy-gateway-system$' --namespace cubestack-system
# Setting the catalog hostname enables catalog publishing.
expect_render catalog-set present '^[[:space:]]*- --gateway-catalog-hostname=ai\.example\.com$' --set gateway.catalogHostname=ai.example.com
# The retired gateway.domain is inert: a values file that still carries it must
# render nothing (the flag is gone from the manager) rather than fail the
# release. helm ignores values no template reads.
expect_render domain-retired absent '^[[:space:]]*- --gateway-domain=' --set gateway.domain=example.com
# An emptied name drops --gateway-name (publishing off) while the namespace
# keeps rendering; a custom name is passed verbatim.
expect_render name-empty absent '^[[:space:]]*- --gateway-name=' --namespace cubestack-system --set gateway.name=
expect_render name-empty present '^[[:space:]]*- --gateway-namespace=envoy-gateway-system$' --namespace cubestack-system --set gateway.name=
expect_render name-custom present '^[[:space:]]*- --gateway-name=my-gateway$' --set gateway.name=my-gateway
# Emptied dataplane namespace drops its flag alone, leaving environments default-deny.
expect_render dataplane-empty absent '^[[:space:]]*- --gateway-dataplane-namespace=' --set gateway.dataplaneNamespace=
expect_render dataplane-empty present '^[[:space:]]*- --gateway-name=cubestack-gateway$' --set gateway.dataplaneNamespace=
# The namespace follows its value and never the release namespace. The Gateway
# object belongs to the platform and does not move with the release, so an
# install into some other namespace must still render the configured default:
# making --namespace the thing that changed the answer is what the old
# release-namespace coupling did, and what this asserts is gone.
expect_render ns-release present '^[[:space:]]*- --gateway-namespace=envoy-gateway-system$' --namespace cubestack-prod
# All the optional flags empty: reproduce the unconfigured state. Only the
# namespace line is left, and it is asserted present rather than skipped.
expect_render all-empty absent '^[[:space:]]*- --gateway-(name|catalog-hostname|dataplane-namespace)=' \
  --set gateway.name= --set gateway.catalogHostname= --set gateway.dataplaneNamespace=
expect_render all-empty present '^[[:space:]]*- --gateway-namespace=envoy-gateway-system$' \
  --set gateway.name= --set gateway.catalogHostname= --set gateway.dataplaneNamespace=
# The namespace follows its value verbatim, and an emptied value must NOT drop
# the flag: an omitted flag falls back to cubestack-system inside the manager,
# a namespace neither install path configured. These two pin the `| default`
# choice — the first proves a custom value reaches the manager, the second
# proves an empty one cannot silently re-point it.
expect_render gw-ns-custom present '^[[:space:]]*- --gateway-namespace=platform-gateway$' --set gateway.namespace=platform-gateway
expect_render gw-ns-empty present '^[[:space:]]*- --gateway-namespace=envoy-gateway-system$' --set gateway.namespace=
# The retired gateway.className is inert, like gateway.domain above: the value
# only ever fed the Gateway object this chart no longer ships, so a values file
# still carrying it must render nothing rather than fail the release.
expect_render class-retired absent '^[[:space:]]*gatewayClassName:' --set gateway.className=my-class
# The L4 port pool always renders, and follows its values verbatim: the range
# decides which ports the controller may allocate, so a value that did not
# reach the manager would make environments collide on ports the platform
# Gateway's dataplane Service does not carry.
expect_render defaults present '^[[:space:]]*- --l4-port-range-start=20000$'
expect_render defaults present '^[[:space:]]*- --l4-port-range-end=20999$'
expect_render l4-range-custom present '^[[:space:]]*- --l4-port-range-start=30000$' --set l4PortRange.start=30000
expect_render l4-range-custom present '^[[:space:]]*- --l4-port-range-end=30999$' --set l4PortRange.end=30999

# The RDMA extended resource names also always render, and follow their values
# verbatim. They are defined by the cluster's shared device plugin, not by this
# chart, so a name that did not reach the manager would leave every RDMA
# environment requesting a resource no node advertises — and its pods pending,
# with nothing in the environment's own spec to explain why.
expect_render defaults present '^[[:space:]]*- --rdma-ib-resource=rdma/ib_shared_devices$'
expect_render defaults present '^[[:space:]]*- --rdma-roce-resource=rdma/roce_shared_devices$'
expect_render rdma-custom present '^[[:space:]]*- --rdma-ib-resource=example\.com/ib$' --set rdma.ibResource=example.com/ib
expect_render rdma-custom present '^[[:space:]]*- --rdma-roce-resource=example\.com/roce$' --set rdma.roceResource=example.com/roce

# The chart ships no Gateway and no ClientTrafficPolicy: the platform owns both
# (test/e2e/assets/gateway.yaml is the reference shape it applies, and the chart
# README documents them as prerequisites). Assert they are absent from the
# render, so a resource added back under config/default — or a template left
# behind under templates/ — cannot quietly put this chart back in the business
# of owning an object whose lifecycle the platform decides.
#
# `kind:` is anchored so that `GatewayClass` and the manager's own `gateways`
# RBAC rules cannot be mistaken for the object. `helm template` does not render
# crds/, which is why the CRDs' `spec.names.kind: Gateway` lines are out of this
# render too — the same reason the EnvoyProxy assertion below works.
expect_render defaults absent '^[[:space:]]*kind: Gateway$'
expect_render defaults absent '^[[:space:]]*kind: ClientTrafficPolicy$'
# The chart must not ship a dataplane of its own. The proxy Service type and
# the proxy image live on the EnvoyProxy the GatewayClass references, and a
# Gateway that references one of its own would silently replace the class's
# whole provider config instead of merging with it.
expect_render defaults absent '^[[:space:]]*kind: EnvoyProxy$'
expect_render defaults absent '^[[:space:]]*parametersRef:'

# The manager image's tag defaults to the chart's appVersion. Read the expected
# tag from Chart.yaml so a version bump cannot break this gate.
CHART_APP_VERSION="$(helm show chart "${CHART}" | awk '/^appVersion:/{gsub(/"/,"",$2); print $2}')"
expect_render defaults present "^[[:space:]]*image: \"harbor\.isuanova\.com/suanova/cubestack-controller-manager:${CHART_APP_VERSION}\"$" --namespace cubestack-system
# An explicit tag still wins, which is how a rolling install points at `latest`.
expect_render image-tag-set present '^[[:space:]]*image: "harbor\.isuanova\.com/suanova/cubestack-controller-manager:v9\.9\.9"$' --set image.tag=v9.9.9

echo "chart resources regenerated under ${CHART}"
