apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubestack-portal-chart.fullname" . }}-session-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cubestack-portal-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "cubestack-portal-chart.chart" . }}
type: Opaque
data:
  {{- if .Values.secrets.sessionSecret.existingSecret }}
  {{- /* Use existing secret value */}}
  {{- else }}
  session-secret: {{ (randAlphaNum (int .Values.secrets.sessionSecret.length)) | b64enc | quote }}
  {{- end }}
