apiVersion: v1
kind: Service
metadata:
  name: {{ include "cubestack-portal-chart.serviceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cubestack-portal-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "cubestack-portal-chart.chart" . }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "cubestack-portal-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
