"use client";

// 配置 tab — model selection, LLM catalog, system prompt, instance status,
// confirmation policy + allowlist, mirroring the reference
// AgentView (cubepilot web/src/views/AgentView.tsx).

import { Box } from "@mui/material";
import { ReactNode, useCallback, useEffect, useState } from "react";

import type {
  AgentConfig,
  AgentStatus,
  AllowlistRule,
  ConfirmView,
  LlmModel,
} from "@/lib/cubepilot/types";
import { useI18n } from "@/lib/i18n";

import { fmtUptime } from "./format";
import { Btn, Card, CardHead, CpInput, CpTextArea, Icons, Pill, inputSx, monoSx, useToast } from "./ui";

const ruleKey = (r: AllowlistRule) => r.pattern + "|" + (r.argPattern || "");

export function ConfigPane() {
  const { t } = useI18n();
  const { showToast, toastView } = useToast();

  const [config, setConfig] = useState<AgentConfig>({ exists: false, model: "", systemPrompt: "" });
  const [status, setStatus] = useState<AgentStatus | null>(null);
  const [confirm, setConfirm] = useState<ConfirmView | null>(null);
  const [policySel, setPolicySel] = useState("");
  const [llms, setLlms] = useState<LlmModel[]>([]);
  const [llmForm, setLlmForm] = useState({ name: "", endpoint: "", apiKey: "", public: false });
  const [editingModel, setEditingModel] = useState<string | null>(null);
  const [llmBusy, setLlmBusy] = useState(false);
  const [confirmBusy, setConfirmBusy] = useState(false);
  const [ruleForm, setRuleForm] = useState({ pattern: "", argPattern: "" });
  const [saving, setSaving] = useState(false);

  const loadAll = useCallback(async () => {
    const get = async <T,>(path: string) => {
      const res = await fetch(path);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return (await res.json()) as T;
    };
    try {
      const [cfgRes, stRes, cfRes, llmRes] = await Promise.all([
        get<{ config: AgentConfig }>("/api/cubepilot/agent/config"),
        get<AgentStatus>("/api/cubepilot/agent/status"),
        get<ConfirmView>("/api/cubepilot/agent/confirm"),
        get<{ llms: LlmModel[] }>("/api/cubepilot/llms"),
      ]);
      setConfig(cfgRes.config);
      setStatus(stRes);
      setConfirm(cfRes);
      setPolicySel(cfRes.override);
      setLlms(llmRes.llms);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    }
  }, [showToast, t]);

  // Mount-only: loadAll's identity changes every render (its t dep is
  // regenerated by useI18n), and the fetched data is locale-neutral, so a
  // load-once effect is what we want.
  /* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
  useEffect(() => {
    void loadAll();
  }, []);
  /* eslint-enable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

  async function saveConfig() {
    if (saving) return;
    setSaving(true);
    try {
      const res = await fetch("/api/cubepilot/agent/config", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ config: { model: config.model, systemPrompt: config.systemPrompt } }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const body = (await res.json()) as { config: AgentConfig };
      setConfig(body.config);
      showToast(t("cubepilot.config.saved"));
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    } finally {
      setSaving(false);
    }
  }

  // ── confirmations ──

  async function persistConfirm(body: { confirmPolicy?: string; allowlist?: AllowlistRule[] }) {
    if (confirmBusy) return;
    setConfirmBusy(true);
    try {
      const res = await fetch("/api/cubepilot/agent/confirm", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const v = (await res.json()) as ConfirmView;
      setConfirm(v);
      setPolicySel(v.override);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    } finally {
      setConfirmBusy(false);
    }
  }

  function changePolicy(value: string) {
    setPolicySel(value);
    void persistConfirm({ confirmPolicy: value });
  }

  function addRule() {
    const pattern = ruleForm.pattern.trim();
    if (!pattern) {
      showToast(t("cubepilot.config.errPattern"));
      return;
    }
    if (!confirm) return;
    const entry: AllowlistRule = { pattern, argPattern: ruleForm.argPattern.trim() || undefined, owned: true };
    if (confirm.allowlist.some((r) => ruleKey(r) === ruleKey(entry))) {
      showToast(t("cubepilot.config.dupeRule"));
      return;
    }
    void persistConfirm({ allowlist: [...confirm.allowlist, entry] });
    setRuleForm({ pattern: "", argPattern: "" });
    showToast(t("cubepilot.config.ruleAdded"));
  }

  function removeRule(key: string) {
    if (!confirm) return;
    void persistConfirm({ allowlist: confirm.allowlist.filter((r) => ruleKey(r) !== key) });
    showToast(t("cubepilot.config.ruleRemoved"));
  }

  function resetConfirm() {
    setPolicySel("");
    void persistConfirm({ confirmPolicy: "", allowlist: [] });
  }

  // ── LLM catalog ──

  function resetLlmForm() {
    setLlmForm({ name: "", endpoint: "", apiKey: "", public: false });
    setEditingModel(null);
  }

  function startEditLlm(m: LlmModel) {
    // The stored key is never sent to the browser; a blank key on edit keeps
    // the current credential.
    setLlmForm({ name: m.name, endpoint: m.endpoint, apiKey: "", public: !m.keyed });
    setEditingModel(m.name);
  }

  async function removeLlm(name: string) {
    if (llmBusy) return;
    if (!window.confirm(t("cubepilot.config.removeConfirm", { name }))) return;
    setLlmBusy(true);
    try {
      const res = await fetch(`/api/cubepilot/llms/${encodeURIComponent(name)}`, { method: "DELETE" });
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as { error?: string };
        throw new Error(body.error ?? `HTTP ${res.status}`);
      }
      showToast(t("cubepilot.config.llmRemoved"));
      if (editingModel === name) resetLlmForm();
      const body = (await fetch("/api/cubepilot/llms")).json() as Promise<{ llms: LlmModel[] }>;
      setLlms((await body).llms);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    } finally {
      setLlmBusy(false);
    }
  }

  async function submitLlm() {
    if (llmBusy) return;
    if (!llmForm.endpoint.trim()) {
      showToast(t("cubepilot.config.errEndpoint"));
      return;
    }
    if (!editingModel && !llmForm.name.trim()) {
      showToast(t("cubepilot.config.errName"));
      return;
    }
    if (!editingModel && !llmForm.apiKey && !llmForm.public) {
      showToast(t("cubepilot.config.errKey"));
      return;
    }
    setLlmBusy(true);
    try {
      if (editingModel) {
        const res = await fetch(`/api/cubepilot/llms/${encodeURIComponent(editingModel)}`, {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ endpoint: llmForm.endpoint, apiKey: llmForm.apiKey || undefined, public: llmForm.public }),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        showToast(t("cubepilot.config.llmUpdated"));
      } else {
        const res = await fetch("/api/cubepilot/llms", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            name: llmForm.name,
            endpoint: llmForm.endpoint,
            apiKey: llmForm.apiKey || undefined,
            public: llmForm.public,
          }),
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        showToast(t("cubepilot.config.llmAdded"));
      }
      resetLlmForm();
      const body = (await fetch("/api/cubepilot/llms")).json() as Promise<{ llms: LlmModel[] }>;
      setLlms((await body).llms);
    } catch (e) {
      showToast(t("cubepilot.failed", { error: String(e) }), "error");
    } finally {
      setLlmBusy(false);
    }
  }

  const hasInstance = !!status?.exists;
  const allowlistPolicy = confirm?.confirmPolicy === "Allowlist";

  return (
    <Box data-od-id="cp-config-pane">
      {/* head */}
      <Box sx={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: "16px", mb: "16px", flexWrap: "wrap" }}>
        <Box>
          <Box sx={{ fontSize: 18, fontWeight: 650, letterSpacing: "-0.01em" }}>{t("cubepilot.config.title")}</Box>
          <Box sx={{ fontSize: 13, color: "text.secondary", mt: "3px" }}>{t("cubepilot.config.desc")}</Box>
        </Box>
        <Btn variant="primary" onClick={() => void saveConfig()} disabled={!hasInstance || saving} title={!hasInstance ? t("cubepilot.config.saveDisabled") : undefined} data-od-id="cp-config-save">
          {Icons.check()}
          {t("cubepilot.config.save")}
        </Btn>
      </Box>

      <Box sx={{ display: "grid", gridTemplateColumns: "1fr 320px", gap: "14px", alignItems: "start" }}>
        {/* ── left column ── */}
        <Box sx={{ display: "flex", flexDirection: "column", gap: "14px", minWidth: 0 }}>
          {/* Model & Runtime */}
          <Card data-od-id="cp-config-model">
            <CardHead title={t("cubepilot.config.modelTitle")} hint={t("cubepilot.config.modelHint")} />
            <Box sx={{ p: "16px", display: "flex", flexDirection: "column", gap: "14px" }}>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.config.model")}</Box>
                <Box
                  component="select"
                  aria-label={t("cubepilot.config.model")}
                  value={config.model || ""}
                  onChange={(e) => setConfig((c) => ({ ...c, model: e.target.value }))}
                  sx={inputSx}
                  data-od-id="cp-config-model-select"
                >
                  <Box component="option" value="" disabled>
                    {t("cubepilot.config.modelSelect")}
                  </Box>
                  {llms.map((m) => (
                    <Box key={m.name} component="option" value={m.name}>
                      {m.name}
                    </Box>
                  ))}
                </Box>
                {llms.length === 0 ? (
                  <Box sx={{ fontSize: 12, color: "#e15c5c" }}>{t("cubepilot.config.noModels")}</Box>
                ) : null}
              </Box>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.config.runtime")}</Box>
                {/* Single fixed runtime; the no-op onChange silences React's
                    value-without-onChange warning. */}
                <Box component="select" aria-label={t("cubepilot.config.runtime")} value="CubePilot" onChange={() => {}} sx={inputSx}>
                  <Box component="option" value="CubePilot">CubePilot</Box>
                </Box>
              </Box>
            </Box>
          </Card>

          {/* LLM Config */}
          <Card data-od-id="cp-config-llm">
            <CardHead title={t("cubepilot.config.llmTitle")} hint={t("cubepilot.config.llmHint")} />
            <Box sx={{ p: "16px", display: "flex", flexDirection: "column", gap: "8px" }}>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "8px", mb: "12px" }}>
                {llms.length === 0 ? (
                  <Box sx={{ fontSize: 13, color: "text.secondary" }}>{t("cubepilot.config.llmNone")}</Box>
                ) : null}
                {llms.map((m) => (
                  <Box key={m.name} sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "8px", fontSize: 13 }}>
                    <Box sx={{ ...monoSx, fontSize: 12.5 }}>{m.name}</Box>
                    <Box sx={{ display: "flex", alignItems: "center", gap: "6px" }}>
                      <Pill variant="neutral">{m.keyed ? t("cubepilot.config.llmKeyed") : t("cubepilot.config.llmPublic")}</Pill>
                      <Btn small variant="ghost" disabled={llmBusy} onClick={() => startEditLlm(m)}>
                        {t("cubepilot.config.llmEdit")}
                      </Btn>
                      <Btn small variant="ghost" disabled={llmBusy} onClick={() => void removeLlm(m.name)}>
                        {t("cubepilot.config.llmRemove")}
                      </Btn>
                    </Box>
                  </Box>
                ))}
              </Box>
              {editingModel ? (
                <Box sx={{ fontSize: 12.5, color: "text.secondary", mb: "4px" }}>{t("cubepilot.config.llmEditing", { name: editingModel })}</Box>
              ) : (
                <CpInput
                  placeholder={t("cubepilot.config.llmNamePh")}
                  aria-label={t("cubepilot.config.llmNamePh")}
                  value={llmForm.name}
                  onChange={(e) => setLlmForm((f) => ({ ...f, name: e.target.value }))}
                />
              )}
              <CpInput
                placeholder={t("cubepilot.config.llmEndpointPh")}
                aria-label={t("cubepilot.config.llmEndpointPh")}
                value={llmForm.endpoint}
                onChange={(e) => setLlmForm((f) => ({ ...f, endpoint: e.target.value }))}
              />
              <Box sx={{ fontSize: 12, color: "text.secondary", my: "2px" }}>{t("cubepilot.config.llmEndpointHint")}</Box>
              <CpInput
                type="password"
                disabled={llmForm.public}
                placeholder={editingModel ? t("cubepilot.config.llmKeyPhEdit") : t("cubepilot.config.llmKeyPh")}
                aria-label={t("cubepilot.config.llmKeyPh")}
                value={llmForm.apiKey}
                onChange={(e) => setLlmForm((f) => ({ ...f, apiKey: e.target.value }))}
              />
              <Box
                component="label"
                sx={{ display: "flex", alignItems: "center", gap: "8px", fontSize: 13, mb: "10px", cursor: "pointer" }}
              >
                <input
                  type="checkbox"
                  checked={llmForm.public}
                  onChange={(e) => setLlmForm((f) => ({ ...f, public: e.target.checked, apiKey: e.target.checked ? "" : f.apiKey }))}
                />
                {t("cubepilot.config.llmPublicLabel")}
              </Box>
              <Btn variant="primary" disabled={llmBusy} onClick={() => void submitLlm()} sx={{ width: "100%" }} data-od-id="cp-config-llm-submit">
                {llmBusy ? t("cubepilot.config.llmSaving") : editingModel ? t("cubepilot.config.llmSave") : t("cubepilot.config.llmAdd")}
              </Btn>
              {editingModel ? (
                <Btn disabled={llmBusy} onClick={resetLlmForm} sx={{ width: "100%", mt: "6px" }}>
                  {t("cubepilot.config.llmCancel")}
                </Btn>
              ) : null}
            </Box>
          </Card>

          {/* System Prompt */}
          <Card data-od-id="cp-config-prompt">
            <CardHead title={t("cubepilot.config.promptTitle")} hint={t("cubepilot.config.promptHint")} />
            <Box sx={{ p: "16px" }}>
              <CpTextArea
                rows={6}
                placeholder={t("cubepilot.config.promptPh")}
                aria-label={t("cubepilot.config.promptTitle")}
                value={config.systemPrompt || ""}
                onChange={(e) => setConfig((c) => ({ ...c, systemPrompt: e.target.value }))}
                data-od-id="cp-config-prompt-input"
              />
            </Box>
          </Card>
        </Box>

        {/* ── instance status ── */}
        <Card sx={{ position: "sticky", top: 70 }} data-od-id="cp-config-status">
          <CardHead
            title={t("cubepilot.config.instTitle")}
            actions={<Pill variant={hasInstance ? "ok" : "neutral"} dot pulse={hasInstance}>{hasInstance ? t("cubepilot.config.instRunning") : "—"}</Pill>}
          />
          <Box sx={{ p: "16px", display: "grid", gridTemplateColumns: "1fr", gap: "12px" }}>
            {status ? (
              <>
                <InstRow k={t("cubepilot.config.instId")} v={<Box component="span" sx={{ ...monoSx, fontSize: 12 }}>{status.id || "-"}</Box>} />
                <InstRow k={t("cubepilot.config.instPhase")} v={status.phase || "-"} />
                <InstRow k={t("cubepilot.config.instUptime")} v={fmtUptime(status.uptimeSeconds)} />
                <InstRow k={t("cubepilot.config.instImage")} v={<Box component="span" sx={{ ...monoSx, fontSize: 11.5 }}>{status.gatewayImage || "-"}</Box>} />
                <InstRow k={t("cubepilot.config.instVolume")} v={<Box component="span" sx={{ ...monoSx, fontSize: 11.5 }}>data-{status.user}</Box>} />
              </>
            ) : null}
          </Box>
        </Card>
      </Box>

      {/* ── confirmations ── */}
      <Card sx={{ mt: "14px" }} data-od-id="cp-config-confirm">
        <CardHead title={t("cubepilot.config.confirmTitle")} hint={t("cubepilot.config.confirmHint")} />
        <Box sx={{ p: "16px", display: "flex", flexDirection: "column", gap: "14px" }}>
          <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
            <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.config.policy")}</Box>
            <Box
              component="select"
              aria-label={t("cubepilot.config.policy")}
              value={policySel}
              disabled={!confirm?.exists || confirmBusy}
              onChange={(e) => changePolicy(e.target.value)}
              sx={inputSx}
              data-od-id="cp-config-policy"
            >
              <Box component="option" value="">{t("cubepilot.config.policyFollow", { policy: confirm?.templatePolicy || "Allowlist" })}</Box>
              <Box component="option" value="Allowlist">{t("cubepilot.config.policyAllowlist")}</Box>
              <Box component="option" value="AlwaysAsk">{t("cubepilot.config.policyAlwaysAsk")}</Box>
              <Box component="option" value="None">{t("cubepilot.config.policyNone")}</Box>
            </Box>
            {confirm?.exists ? (
              <Box sx={{ fontSize: 12, color: "text.secondary" }}>
                {t("cubepilot.config.effective")}: <Pill variant="neutral">{confirm.confirmPolicy || "None"}</Pill>{" "}
                {confirm.override ? t("cubepilot.config.override") : t("cubepilot.config.inherited")}
              </Box>
            ) : null}
          </Box>

          {allowlistPolicy ? (
            <>
              <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                <Box component="label" sx={{ fontSize: 12.5, color: "text.secondary", fontWeight: 550 }}>{t("cubepilot.config.allowlistTitle")}</Box>
                <Box sx={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                  {confirm?.allowlist.map((r) => (
                    <Box key={ruleKey(r)} sx={{ display: "flex", alignItems: "center", gap: "9px", p: "8px 12px", border: 1, borderColor: "divider", borderRadius: 6, bgcolor: "var(--surface)" }}>
                      <Box sx={{ color: "text.secondary", display: "flex" }}>{Icons.tool({ size: 13 })}</Box>
                      <Box component="span" sx={{ ...monoSx, fontSize: 12, flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }} title={r.label || r.pattern}>
                        {r.label || r.pattern}
                      </Box>
                      <Pill variant={r.owned ? "accent" : "neutral"}>{r.owned ? t("cubepilot.config.ruleYours") : t("cubepilot.config.rulePlatform")}</Pill>
                      {r.owned ? (
                        <Btn small disabled={confirmBusy} onClick={() => removeRule(ruleKey(r))}>
                          {t("cubepilot.config.ruleRemove")}
                        </Btn>
                      ) : null}
                    </Box>
                  ))}
                  {confirm && confirm.allowlist.length === 0 ? (
                    <Box sx={{ color: "text.secondary", fontSize: 13 }}>{t("cubepilot.config.allowlistEmpty")}</Box>
                  ) : null}
                </Box>
              </Box>
              <Box sx={{ display: "flex", gap: "6px" }}>
                <CpInput
                  placeholder={t("cubepilot.config.rulePatternPh")}
                  aria-label={t("cubepilot.config.rulePatternPh")}
                  value={ruleForm.pattern}
                  onChange={(e) => setRuleForm((f) => ({ ...f, pattern: e.target.value }))}
                  sx={{ flex: 1, minWidth: 0, ...monoSx, fontSize: 12.5 }}
                  data-od-id="cp-config-rule-pattern"
                />
                <CpInput
                  placeholder={t("cubepilot.config.ruleArgPh")}
                  aria-label={t("cubepilot.config.ruleArgPh")}
                  value={ruleForm.argPattern}
                  onChange={(e) => setRuleForm((f) => ({ ...f, argPattern: e.target.value }))}
                  sx={{ flex: 1, minWidth: 0, ...monoSx, fontSize: 12.5 }}
                />
                <Btn disabled={confirmBusy} onClick={addRule}>
                  {t("cubepilot.config.ruleAdd")}
                </Btn>
              </Box>
              <Btn disabled={confirmBusy} onClick={resetConfirm}>
                {t("cubepilot.config.resetDefault")}
              </Btn>
            </>
          ) : (
            <Box sx={{ fontSize: 13, color: "text.secondary" }}>
              {confirm?.confirmPolicy === "AlwaysAsk"
                ? t("cubepilot.config.policyAlwaysAskNote")
                : t("cubepilot.config.policyNoneNote")}
            </Box>
          )}
        </Box>
      </Card>

      {toastView}
    </Box>
  );
}

function InstRow({ k, v }: { k: string; v: ReactNode }) {
  return (
    <Box sx={{ display: "flex", flexDirection: "column", gap: "3px" }}>
      <Box sx={{ fontSize: 11.5, color: "text.secondary" }}>{k}</Box>
      <Box sx={{ fontSize: 13 }}>{v}</Box>
    </Box>
  );
}
